const defaltSites = {
  stackoverflow: {
    name: 'Stack Overflow',
    url: 'https://stackoverflow.com/questions/',
    checked: true,
    default: true,
    // groups: [groups.communities],
    groups: ['communities'],
    // initValue: [],
  },
  stackexchange: {
    name: 'Stackexchange',
    url: 'https://www.stackexchange.com',
    checked: true,
    default: true,
    groups: ['communities'],
    // groups: [groups.communities],
  },
  reddit: {
    name: 'Reddit',
    url: 'https://www.reddit.com/',
    checked: true,
    default: true,
    groups: ['communities'],
    // groups: [groups.communities],
  },
  quora: {
    name: 'Quora',
    url: 'https://www.quora.com/',
    checked: true,
    default: true,
    groups: ['communities'],
    // groups: [groups.communities],
  },
  devto: {
    name: 'Dev.to – Community',
    url: 'https://dev.to',
    checked: false,
    default: false,
    groups: ['communities', 'sites', 'blog'],
    // groups: [groups.communities],
  },
  hackernews: {
    name: 'Hacker News',
    url: 'https://news.ycombinator.com/',
    checked: false,
    default: false,
    groups: ['communities'],
    // groups: [groups.communities],
  },
  hackernoon: {
    name: 'Hackernoon',
    url: 'https://hackernoon.com',
    checked: false,
    default: false,
    groups: ['communities'],
    // groups: [groups.communities],
  },
  freecodecamp: {
    name: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/forum/',
    checked: false,
    default: false,
    groups: ['communities'],
    // groups: [groups.communities],
  },
  sitepoint: {
    name: 'Site Point – Community',
    url: 'https://www.sitepoint.com/',
    checked: false,
    default: false,
    groups: ['sites'],
    // groups: [groups.communities],
  },
  spectrum: {
    name: 'Spectrum',
    url: 'https://www.spectrum.chat/',
    checked: false,
    default: false,
    groups: ['communities'],
    // groups: [groups.communities],
  },
  codeproject: {
    name: 'CodeProject',
    url: 'https://www.codeproject.com/',
    checked: false,
    default: false,
    groups: ['communities'],
    // groups: [groups.communities],
  },
};

export default defaltSites;
